services:
  
  

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "4318:4318"
      - "16686:16686"
    restart: unless-stopped
    networks:
        - mylocal

  app:
    build: .
    container_name: kata_test_app
    profiles: ['local-environment'] # только при запуске с этим профилем сервис будет запущен
    env_file:
      - .env
    ports:
      - "8181:8181"
      - "8182:8182"
    restart: unless-stopped
    networks:
        - mylocal
    depends_on:
      - db
   

  client:
    build: .
    command: ["./bin/client"] 
    container_name: kata_test_app_client
    profiles: ['local-environment'] # только при запуске с этим профилем сервис будет запущен
    env_file:
      - .env
    restart: unless-stopped
    networks:
        - mylocal
    depends_on:
    - app
    
   
  db:
    image: postgres:latest
    container_name: kata_test_db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    ports:
        - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
        - mylocal

  migrations:
     build: ./migrations
     container_name: kata_test_migrations
     env_file:
      - .env
     environment:
      GOOSE_DRIVER: ${GOOSE_DRIVER}
      GOOSE_DBSTRING: ${GOOSE_DSN}
     restart: unless-stopped
     networks:
        - mylocal
     depends_on:
      - db
       

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_cont
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
        - mylocal


networks:
    mylocal:
        driver: bridge

volumes:
    pgdata: